= Rust
:toc:
:toc-title:

== Introduction

This document provides an overview of the Rust programming language, including its key features, data types, and installation instructions. Rust is a systems programming language focused on safety, speed, and concurrency. It accomplishes memory safety without using garbage collection, making it useful for a range of applications from embedded devices to web services.

=== Built-in types

Rust has several built-in types for handling different kinds of data:

* **Integral Types**: These include `u8`, `i32`, and so on. The first character indicates whether the number is signed (`i`) or unsigned (`u`), and the number after that indicates the size in bits (8-bit, 32-bit, etc.).

.Integer Types in Rust
|===
| Length | Signed | Unsigned
| 8-bit  | i8     | u8
| 16-bit | i16    | u16 
| 32-bit | i32    | u32
| 64-bit | i64    | u64
| 128-bit| i128   | u128
| arch   | isize  | usize
|===

`Signed` variants can store numbers from `-(2^(n - 1))` to `2^(n - 1) - 1` inclusive, where `n` is the number of bits that variant uses. So an `i8` can store numbers from `-(2^7)` to `2^7 - 1`, which equals `-128` to `127`.

`Unsigned` variants can store numbers from `0` to `2^n - 1`, where `n` is the number of bits that variant uses. So a `u8` can store numbers from `0` to `255`.

* **Floating-Point Types**: These are `f64` and `f32`, which represent double precision floating point numbers and single precision ones respectively.
* **Numeric Operations**: Rust has several traits that allow you to do numeric operations on types, including addition (`Add`), subtraction (`Sub`), multiplication (`Mul`), division (`Div`), and so forth. These are defined in the `std::ops` module.
* **Boolean Type**: This is a type that can have only two values, `true` or `false`. It's often used for control flow in your programs.
* **Character Types**: Rust's `char` type represents a Unicode Scalar Value, meaning it can represent any valid character in many languages and beyond.
* **Array Type**: This is a fixed-size collection of elements with the same type. For example, `let arr: [i32; 5] = [1, 2, 3, 4, 5];` declares an array of five `i32` values.
* **Tuple Type**: This is a general-purpose data structure that can hold different types and amounts of data. For example, `let tup: (i32, f64, u8) = (500, 60.4, 1);` declares a tuple with an `i32`, `f64`, and `u8` value.
* **String Type**: Rust's `String` type is a growable UTF-8 encoded string type that can be easily modified like you would do in Python or Java.
* **Pointer Types**: These types represent the memory addresses of values, and there are two kinds: `Box<T>` for allocating on the heap (and thus allowing large amounts of data), and `&T` for references to other values.
* **Option Type**: Rust's `Option` type is used when a value could be something or nothing. This can help prevent null pointer exceptions at compile time. The variants are `Some(T)` (which represents a value of type `T`) and `None`, which means no value.

Remember that in Rust, types must be declared and annotated as such. You also have the flexibility to create your own custom data structures using structs or enums.

For more information on these and other basic types, consider referring to the official Rust documentation (https://doc.rust-lang.org/std/). It provides comprehensive explanations for all of these and many others in detail.

== Install and Update Rust

* First, head over to the link: https://doc.rust-lang.org/book/ch01-01-installation.html[Installation] page and follow the instructions:

    $ curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh

* To update your Rust installation, use the following command:

    $ rustup update

== Building a Rust project and managing packages with Cargo

Create a file with a `.rs` extension, insert Rust code, then compile the file:

    $ rustc script.rs

When you install `Rustup`, you’ll also get the latest stable version of the Rust build tool and package manager, also known as Cargo.

`Cargo` does lots of things:

* *cargo new hello-rust*: generates a `Hello, world!` project

    project_hello_world
    ├── Cargo.lock
    ├── Cargo.toml
    ├── src
    │   └── main.rs
    └── target
        ├── CACHEDIR.TAG
        └── debug

* *cargo build*: build your project
* *cargo run*: run your project
* *cargo test*: test your project
* *cargo doc*: build documentation for your project
* *cargo publish*: publish a library to `crates.io`

== Workflow to build and release a Rust project

Here is a workflow to build and release a Rust project:

1. Open your terminal in your project directory (where `Cargo.toml` is located).
2. To compile the project, without optimizations for speed or size, use the command:

    $ cargo build

    This produces a binary file under `target/debug/`. You can run this program with:

    $ ./target/debug/your_program

3. If you want to optimize your project for speed and size, use the command:

    $ cargo build --release

    This produces a binary file under `target/release/`. You can run this program with:

    $ ./target/release/your_program

4. If you want to specify which executable to run, use the `--bin` argument followed by your chosen binary name. For instance, if you have multiple executables in your project and you're interested in running `script`:

    $ cargo run --bin script
    $ ./target/release/script

5. After finishing your work on GitHub or other platforms, to publish the package to crates.io for others to use:
    * Increment the version number in `Cargo.toml` (under `[package]`) according to semantic versioning rules.
    * Login into your account with `cargo login <your token>` command in the terminal where `<your token>` is the API Token which you can generate from https://crates.io/me.
    * Publish the package using the `cargo publish` command in the terminal.
    * Test the published package by creating a new project and using it as a dependency with its name and version number.

== Running project in bin

    cd project_rust
    cargo run --bin variable
    cargo run --bin mutability
    cargo run --bin shadow
    cargo run --bin type

== Generic Notes

* In Rust, variables are immutable by default.
* `let` creates a new variable:

    let apples = 5;

* To make a variable mutable, we add `mut` before the variable name:

    let apples = 5; // immutable
    let mut bananas = 5; // mutable

* The `::` syntax in the `::new` line indicates that `new` is an associated function of the `String` type:

    let mut guess = String::new();

* `let mut guess = String::new();` creates a mutable variable that is currently bound to a new, empty instance of a `String`:

    io::stdin()
        .read_line(&mut guess)

* Call the `stdin` function from the `io` module:

    io::stdin()
        .read_line(&mut guess)

* Running the `cargo doc --open` command will build documentation provided by all your dependencies locally and open it in your browser.
* A vector is a similar collection type provided by the standard library that is allowed to grow or shrink in size.
* Functions can return values to the code that calls them. We don’t name return values, but we must declare their type after an arrow (`->`):

    fn five() -> i32 {
        5
    }

* Statements are instructions that perform some action and do not return a value. Creating a variable and assigning a value to it with the `let` keyword is a statement:

    let x = 3;

* Expressions evaluate to a resultant value:

    {
        let x = 3;
        x + 1
    }

* Expressions do not include ending semicolons. If you add a semicolon to the end of an expression, you turn it into a statement, and it will then not return a value.

== Working with Candle

Install `Candle` for your Rust project:

    cargo add --git https://github.com/huggingface/candle.git candle-core

== Reference

* https://www.rust-lang.org/learn/get-started
* https://doc.rust-lang.org/rust-by-example/
* https://pola.rs/
* https://doc.rust-lang.org/cargo/